### ISSUE TITLE
watch sequence fails

### ISSUE THREAD

**Issue by daviestar** [bholloway/gulp-watch-sequence#1]
I found I couldn't get your example to work with error along the lines of '1st argument to gulp-watch must be string or array', so I changed to this:

``` javascript
gulp.task('default', ['build'], function() {
    var queue = watchSeq(300);
    watch(root+'/**/*.js, queue.getHandler('js', 'rev'));
});
```

(not sure what's going on with the syntax highlighting there.. ignore)

Then got an error from your plugin - 'Elements must be either string or function.'
So inside your plugin I changed:

``` javascript
var sequences = Array.prototype.slice.call(arguments);
console.log(sequences) // ['js', 'rev', undefined]
// ...
getHandler: function () {
  var sequence = Array.prototype.slice.call(arguments);
  return function(files, done) {
    console.log(done) // undefined
    // enqueue.apply(null, sequence.concat(done));
    enqueue.apply(null, sequence);
  }
}
```

And it works.

**Comment by bholloway** [comment]
Sorry for the delay, i have been banned from the  keyboard for the holidays.

This gulp utility was written some time ago and I believe both `gulp-watch` and `gulp` has changed their API.

In the first case it looks like we just need to update the example, since it is using an old `gulp-watch` invocation.

In the case of the `done` handler this is an artefact of the [`run-sequence`](https://www.npmjs.com/package/run-sequence) that was necessary before Gulp 4 defined `gulp.series()`. I am thinking that `run-sequence` needs to be completely removed.

**Comment by bholloway** [comment]
Although @nuba's solution seems to cater for all cases. What do you think @daviestar?

**Comment by daviestar** [comment]
I'm no expert, but looks good to me :+1: 

On your point about `run-sequence` being superseded by `gulp.series()`.. I know gulp v4 isn't done yet, but I have already tried to convert my gulpfile to v4 just to use the `.series()` and `.parallel()` and found it locked me into a pattern which meant I couldn't remake some of my v3 functionality... well I couldn't figure it out anyway.  For example, I couldn't use conditions in my `.series()`, ie. if task a = true, run task b, c and d; else finish. I can with `run-sequence`.

So I think there might still be uses for `run-sequence` and `gulp-watch-sequence` after v4 comes out.

**Comment by bholloway** [comment]
Ok @daviestar I have also made some changes to the `readme.md`. Please let me know if this addresses your concern. I have merged @nuba's fix so that should address the functionality.

I will bump this to `1.0.0` and publish on-risk. But let me know here any final tweaks as I can easily publish a patch.

Thank you both.

**Comment by daviestar** [comment]
Thanks @bholloway and @nuba.  I updated to `v1.0.0` and everything works as expected. Cheers.
